---
ibm_repo: "{{ ibm_root }}/repo"
ibm_shared_path: "{{ ibm_root }}/Shared"
was_repo: "{{ ibm_repo }}/WAS"
jdk_repo: "{{ ibm_repo }}/JDK"
iim_tmp: "{{ ibm_root }}/tmp"
was_user: "{{ ibm_user }}"
was_group: "{{ was_user }}"
state: installed
profile_state: started
was_nd: false
was_version: '9.0'
was_mode: "{{ ibm_mode }}"
was_path: "{{ibm_root}}/WebSphere/AppServer"
was_profiles_path: "{{ was_path }}/profiles"

was_type: "BASE"
was_imcl_package_regex: "com.ibm.websphere.{{ was_type }}.v[0-9]+_([0-9]+.[0-9]+.[0-9]+.[0-9]+)"
was_imcl_package_name: "com.ibm.websphere.{{ was_type }}.v90"
jdk_imcl_package_name: "com.ibm.java.jdk.v8"
