---
ibm_root: "/opt/IBM"
was_root: "{{ ibm_root }}/WebSphere/AppServer"
was_bin: "{{ was_root }}/bin"
wsadmin_cmd: "{{ was_bin }}/wsadmin.sh"
wsadmin_tmp: "/tmp"
wsadmin_params: ""
was_profile_root: "{{ was_root }}/profiles"
